### ISSUE TITLE
*.asn1 extension

### ISSUE THREAD

**Issue by OvermindDL1** [sparticvs/atom-language-asn1#1]
Would be nice if this supported the *.asn1 file extension for the ASN1 format as that extension is used by a variety of generators and it would be nice not to manually select the file type when viewing them.  ^.^

**Comment by sparticvs** [comment]
Noted. I can add that to both `.asn` and `.asn1`.

**Comment by sparticvs** [comment]
After looking, I already had "asn" added. Commit to follow.

**Comment by sparticvs** [comment]
New version is up, let me know if there are any issues.

**Comment by OvermindDL1** [comment]
Awesome, it works.  Thanks much!
